version: '3.5'
name: "workify-services"
services:
  db:
    image: "postgres"
    container_name: "workify-db"
    restart: always
    environment:
    
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "workify"
      POSTGRES_PASSWORD: password 
    volumes:
      - database-data:/var/lib/postgresql-data/
    ports:
      - 8010:5432
volumes:
  database-data: